### ISSUE TITLE
Can't install requirements! Having trouble with `pip install -r requirements.txt`

### ISSUE THREAD

**Issue by NessDan** [kevincon/dotaml#1]
Hey there! I got up to the `pip install -r requirements.txt` step but it seems that most of the packages are no longer supported.

```
(venv)ubuntu@ubuntu-VirtualBox:~/dotaml-master$ pip install -r requirements.txt
Collecting Flask==0.10.1 (from -r requirements.txt (line 1))
/home/ubuntu/dotaml-master/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting Jinja2==2.7.1 (from -r requirements.txt (line 2))
Collecting MarkupSafe==0.18 (from -r requirements.txt (line 3))
Collecting PIL==1.1.7 (from -r requirements.txt (line 4))
  Could not find a version that satisfies the requirement PIL==1.1.7 (from -r requirements.txt (line 4)) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external PIL to allow).
No matching distribution found for PIL==1.1.7 (from -r requirements.txt (line 4))
/home/ubuntu/dotaml-master/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

You can get past the PIL error by adding in `pip install -r requirements.txt --allow-all-external --allow-unverified PIL` but the error comes back up for other packages (which can't be remedied like this)

Other packages I noticed that can't install:
- PIL
- git-remote-helpers
- mimms
- numpy (This one just gave some weird SSL errors, not sure if it worked or not.)
- python-tesseract
- wxPython (The worst offender, could not get this installed with the flags I set above.)

Any work around?

**Comment by kevincon** [comment]
@NessDan can you try the requirements.txt file in my pull request #2 and see if it works for you? 

Note you still need to install gfortran somehow, and on Mac the easiest way is to install it via homebrew with `brew install gcc`. I updated the README with that info as part of #2 as well.

**Comment by NessDan** [comment]
Trying now, will be back with results! Also thank you for the update :smiley:  :+1:

**Comment by NessDan** [comment]
So far, installed some missing dependencies (like you said, gfortran was missing plus some other things!) but now it's stalling when it installs scipy!

`Running setup.py install for scipy`

Freezes there and from Google's Auto Suggest, it seems like this is a common problem:
https://www.google.com/search?q=running%20setup.py%20install%20for%20scipy%20stuck

**Comment by NessDan** [comment]
But pip is no longer erroring out so yay!

**Comment by kevincon** [comment]
Note that scipy takes a while to install (I think it took 10-15 minutes for me), so I would let it run for a while if you're not giving it much time.

You can also run `pip install --verbose -r requirements.txt` and that should also print out more statements to give you more of an idea of what's going on while installing scipy.

**Comment by NessDan** [comment]
Ah, that may have been it! (Or I installed another dependency I needed...)

Regardless, PIP made it through! :D

On a separate note... Running `python app.py` or `python engine.py` returns an error :S 

```
(venv)ubuntu@ubuntu-VirtualBox:~/dotaml-master$ python app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask, render_template, request
ImportError: No module named flask
```

```
(venv)ubuntu@ubuntu-VirtualBox:~/dotaml-master$ python --version
Python 2.7.6
```

**Comment by kevincon** [comment]
It looks like flask isn't installed in the virtual environment. Perhaps you accidentally installed the pip requirements _before_ entering the virtual environment?

While `(venv)` appears on the far left of your command line prompt, try running `pip install -r requirements.txt` and try it again.

If that doesn't work, try just `pip install flask` and let me know what it says.

**Comment by NessDan** [comment]
Ah, you're right!

Any idea why this would be happening though?

```
(venv)ubuntu@ubuntu-VirtualBox:~/dotaml-master$ python app.py
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    engine = Engine(D2KNearestNeighbors())
  File "/home/ubuntu/dotaml-master/k_nearest_neighbors/k_nearest_neighbors.py", line 33, in __init__
    self.recommend_models = pickle.load(input_file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/__init__.py", line 9, in <module>
    from .graph import kneighbors_graph, radius_neighbors_graph
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/graph.py", line 7, in <module>
    from .base import KNeighborsMixin, RadiusNeighborsMixin
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 18, in <module>
    from ..metrics import pairwise_distances
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/__init__.py", line 6, in <module>
    from .metrics import (accuracy_score,
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/metrics.py", line 25, in <module>
    from scipy.spatial.distance import hamming as sp_hamming
  File "/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py", line 91, in <module>
    from .qhull import *
ImportError: /usr/local/lib/python2.7/dist-packages/scipy/spatial/qhull.so: undefined symbol: dgecon_
```

**Comment by kevincon** [comment]
Can you nuke your virtual environment, make a fresh one, and then reinstall the pip requirements to make sure it's not due to some weirdness there? It looks like that might be part of the issue because the scipy-related path in the error (/usr/local/lib/python2.7/dist-packages/scipy/spatial/qhull.so) is referring to your global scipy installation, which is incorrect. It should be trying to use the scipy installed within the virtual environment by pip.

**Comment by kevincon** [comment]
(by nuke I mean delete the folder)

**Comment by NessDan** [comment]
Will do. I've been having some issues with my environment as a whole so I'm doing some spring cleaning. Will report back once it's up to speed :+1:

**Comment by NessDan** [comment]
OK! So I did a clean install of Ubuntu 14.04 and ran pip install. It looked like it was working - it got past a lot of the package installations and compilations but later on I end up with an error at the end:

```
Command /home/ubuntu/dotaml/venv/bin/python -c "import setuptools, tokenize;__file__='/home/ubuntu/dotaml/venv/build/scikit-learn/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5qin5X-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/dotaml/venv/include/site/python2.7 failed with error code 1 in /home/ubuntu/dotaml/venv/build/scikit-learn
Traceback (most recent call last):
  File "/home/ubuntu/dotaml/venv/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/dotaml/venv/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/ubuntu/dotaml/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
```

I also have a log file if that helps!

Also, some of the packages I've installed: `python-virtualenv build-essential git gfortran python-dev python-scipy libopenblas-dev liblapack-dev libatlas-dev libatlas3gf-base python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose`

**Comment by NessDan** [comment]
I GOT IT WORKING!!!

I DON'T KNOW WHAT I DID BUT I GOT IT WORKING!!!

I'LL COME BACK WITH ALL THE DETAILS ONCE I FIGURE IT OUT!!! :smiley:

**Comment by NessDan** [comment]
Not sure which dependencies I really needed, but the fix was simply updating scipy and numpy in the requirements. App runs as expected :+1:

PR #3 has all the details.

**Comment by freyamehta99** [comment]
I've been doing 
 sudo -H pip3 install flask

output

Collecting flask
  Could not find a version that satisfies the requirement flask (from versions: )
No matching distribution found for flask

I don't know why I am not able to install flask using pip
even this
 sudo -H pip3 install flask
is giving output as -
Collecting flask
  Could not find a version that satisfies the requirement flask (from versions: )
No matching distribution found for flask

Without -H -
 sudo pip3 install flask

my output goes like this-
The directory '/home/freya/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/freya/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting flask
  Could not find a version that satisfies the requirement flask (from versions: )
No matching distribution found for flask

please help me install flask

**Comment by NessDan** [comment]
@freyamehta99 it's been a long time since I looked at this project, I remember getting it up and running though. It's possible my repo may work out of the box? I can't promise though.

https://github.com/NessDan/dotaml

**Comment by kevincon** [comment]
> I've been doing
> sudo -H pip3 install flask

@freyamehta99 from your usage of `pip3` it looks like you're trying to use Python 3 to build this project, but this project was only written for Python 2. I don't think it will work under Python 3.

But independent of that, I'm not sure why you aren't able to install Flask using `pip3`. I think you should try creating an issue on the Flask project for getting help on that, they're more suited to help you with this problem than we are: https://github.com/pallets/flask

Anyway, it is exactly these issues with installing `pip` packages that motivated the usage of `virtualenv` for this project. If you follow the steps in the README to use `virtualenv`, I don't think you should have any issues. If you do need more help, please create a new GitHub issue (let's leave this closed one alone).
